import type {
  Clinic,
  User,
  Patient,
  Doctor,
  Appointment,
  MedicalRecord,
  Medicine,
  Transaction,
  QueueItem,
} from "./types"

export const CLINICS: Clinic[] = [
  {
    id: "c1",
    name: "Klinik Sehat Bersama",
    address: "Jl. Sudirman No. 45, Jakarta Pusat",
    phone: "021-5551234",
    email: "info@sehatbersama.id",
    type: "umum",
    status: "aktif",
    totalDokter: 8,
    totalPasien: 1240,
  },
  {
    id: "c2",
    name: "Klinik Medika Prima",
    address: "Jl. Gatot Subroto No. 12, Jakarta Selatan",
    phone: "021-5559876",
    email: "info@medikaprima.id",
    type: "spesialis",
    status: "aktif",
    totalDokter: 15,
    totalPasien: 3200,
  },
  {
    id: "c3",
    name: "Klinik Gigi Senyum Indah",
    address: "Jl. Thamrin No. 7, Jakarta Barat",
    phone: "021-5554321",
    email: "info@senyumindah.id",
    type: "gigi",
    status: "aktif",
    totalDokter: 5,
    totalPasien: 890,
  },
]

export const USERS: User[] = [
  {
    id: "u1",
    name: "Dr. Ahmad Santoso",
    email: "dokter@klinik.id",
    role: "dokter",
    specialization: "Penyakit Dalam",
    licenseNumber: "SIP-2024-001",
    phone: "081234567890",
    clinicIds: ["c1", "c2"],
  },
  {
    id: "u2",
    name: "Budi Setiawan",
    email: "pasien@klinik.id",
    role: "pasien",
    phone: "081234567891",
    clinicIds: ["c1"],
  },
  {
    id: "u3",
    name: "Sari Dewi",
    email: "kasir@klinik.id",
    role: "kasir",
    phone: "081234567892",
    clinicIds: ["c1"],
  },
  {
    id: "u4",
    name: "Rina Wati",
    email: "resepsionis@klinik.id",
    role: "resepsionis",
    phone: "081234567893",
    clinicIds: ["c1"],
  },
  {
    id: "u5",
    name: "Hendra Wijaya",
    email: "apoteker@klinik.id",
    role: "apoteker",
    phone: "081234567894",
    clinicIds: ["c1"],
  },
  {
    id: "u6",
    name: "Dr. Maya Indah",
    email: "pimpinan@klinik.id",
    role: "pimpinan",
    phone: "081234567895",
    clinicIds: ["c1", "c2", "c3"],
  },
]

export const DEMO_CREDENTIALS: Record<string, string> = {
  "dokter@klinik.id": "dokter123",
  "pasien@klinik.id": "pasien123",
  "kasir@klinik.id": "kasir123",
  "resepsionis@klinik.id": "resepsionis123",
  "apoteker@klinik.id": "apoteker123",
  "pimpinan@klinik.id": "pimpinan123",
}

export const PATIENTS: Patient[] = [
  {
    id: "p1",
    name: "Budi Setiawan",
    dob: "1985-03-15",
    gender: "L",
    phone: "081234567891",
    address: "Jl. Melati No. 12, Jakarta",
    bloodType: "O+",
    allergies: ["Penisilin"],
    insurance: "BPJS",
    insuranceNumber: "BPJS-001234",
    registeredAt: "2023-01-15",
    lastVisit: "2026-05-20",
    clinicId: "c1",
  },
  {
    id: "p2",
    name: "Siti Rahayu",
    dob: "1990-07-22",
    gender: "P",
    phone: "081234567802",
    address: "Jl. Mawar No. 5, Jakarta",
    bloodType: "A+",
    allergies: [],
    insurance: "Mandiri",
    insuranceNumber: "MND-005678",
    registeredAt: "2023-03-20",
    lastVisit: "2026-05-22",
    clinicId: "c1",
  },
  {
    id: "p3",
    name: "Joko Susanto",
    dob: "1978-11-08",
    gender: "L",
    phone: "081234567803",
    address: "Jl. Anggrek No. 8, Depok",
    bloodType: "B-",
    allergies: ["Aspirin"],
    registeredAt: "2023-05-10",
    lastVisit: "2026-05-25",
    clinicId: "c1",
  },
  {
    id: "p4",
    name: "Dewi Lestari",
    dob: "1995-02-14",
    gender: "P",
    phone: "081234567804",
    address: "Jl. Kamboja No. 3, Bekasi",
    bloodType: "AB+",
    allergies: [],
    insurance: "BPJS",
    insuranceNumber: "BPJS-002345",
    registeredAt: "2024-01-05",
    lastVisit: "2026-05-27",
    clinicId: "c1",
  },
  {
    id: "p5",
    name: "Rizki Pratama",
    dob: "2000-09-30",
    gender: "L",
    phone: "081234567805",
    address: "Jl. Flamboyan No. 20, Tangerang",
    bloodType: "O-",
    allergies: [],
    registeredAt: "2024-02-18",
    lastVisit: "2026-05-26",
    clinicId: "c1",
  },
  {
    id: "p6",
    name: "Anita Kusuma",
    dob: "1988-12-05",
    gender: "P",
    phone: "081234567806",
    address: "Jl. Dahlia No. 15, Jakarta",
    bloodType: "A-",
    allergies: ["Sulfa"],
    insurance: "Allianz",
    insuranceNumber: "ALZ-003456",
    registeredAt: "2023-08-22",
    lastVisit: "2026-05-28",
    clinicId: "c1",
  },
  {
    id: "p7",
    name: "Hendra Gunawan",
    dob: "1975-05-18",
    gender: "L",
    phone: "081234567807",
    address: "Jl. Seroja No. 9, Bogor",
    bloodType: "B+",
    allergies: [],
    insurance: "BPJS",
    insuranceNumber: "BPJS-003456",
    registeredAt: "2022-11-30",
    lastVisit: "2026-05-15",
    clinicId: "c1",
  },
  {
    id: "p8",
    name: "Fitri Handayani",
    dob: "1993-08-25",
    gender: "P",
    phone: "081234567808",
    address: "Jl. Teratai No. 7, Depok",
    bloodType: "O+",
    allergies: ["Lateks"],
    registeredAt: "2024-03-15",
    lastVisit: "2026-05-28",
    clinicId: "c1",
  },
  {
    id: "p9",
    name: "Tono Wibowo",
    dob: "1970-04-10",
    gender: "L",
    phone: "081234567809",
    address: "Jl. Kuningan No. 3, Jakarta Selatan",
    bloodType: "A+",
    allergies: [],
    insurance: "BPJS",
    insuranceNumber: "BPJS-004567",
    registeredAt: "2022-06-01",
    lastVisit: "2026-05-27",
    clinicId: "c2",
  },
  {
    id: "p10",
    name: "Lia Susanto",
    dob: "1983-09-17",
    gender: "P",
    phone: "081234567810",
    address: "Jl. Senayan No. 11, Jakarta Selatan",
    bloodType: "B+",
    allergies: ["Penisilin"],
    insurance: "Prudential",
    insuranceNumber: "PRD-001122",
    registeredAt: "2023-02-14",
    lastVisit: "2026-05-28",
    clinicId: "c2",
  },
  {
    id: "p11",
    name: "Bram Hadi",
    dob: "1965-12-30",
    gender: "L",
    phone: "081234567811",
    address: "Jl. Rasuna Said No. 5, Jakarta Selatan",
    bloodType: "O-",
    allergies: [],
    registeredAt: "2021-10-20",
    lastVisit: "2026-05-26",
    clinicId: "c2",
  },
  {
    id: "p12",
    name: "Eka Putri",
    dob: "1998-03-05",
    gender: "P",
    phone: "081234567812",
    address: "Jl. Cilandak No. 8, Jakarta Selatan",
    bloodType: "AB+",
    allergies: [],
    insurance: "BPJS",
    insuranceNumber: "BPJS-005678",
    registeredAt: "2024-04-10",
    lastVisit: "2026-05-28",
    clinicId: "c2",
  },
  {
    id: "p13",
    name: "Dian Pratiwi",
    dob: "1991-07-14",
    gender: "P",
    phone: "081234567813",
    address: "Jl. Thamrin No. 20, Jakarta Barat",
    bloodType: "O+",
    allergies: [],
    insurance: "BPJS",
    insuranceNumber: "BPJS-006789",
    registeredAt: "2023-09-05",
    lastVisit: "2026-05-28",
    clinicId: "c3",
  },
  {
    id: "p14",
    name: "Rudi Hartono",
    dob: "1987-02-22",
    gender: "L",
    phone: "081234567814",
    address: "Jl. Mangga Dua No. 4, Jakarta Barat",
    bloodType: "A-",
    allergies: [],
    registeredAt: "2024-01-18",
    lastVisit: "2026-05-27",
    clinicId: "c3",
  },
  {
    id: "p15",
    name: "Nana Sari",
    dob: "2002-11-01",
    gender: "P",
    phone: "081234567815",
    address: "Jl. Grogol No. 9, Jakarta Barat",
    bloodType: "B+",
    allergies: ["Ibuprofen"],
    insurance: "Mandiri",
    insuranceNumber: "MND-007890",
    registeredAt: "2025-03-12",
    lastVisit: "2026-05-28",
    clinicId: "c3",
  },
]

export const DOCTORS: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Ahmad Santoso",
    specialization: "Penyakit Dalam",
    licenseNumber: "SIP-2024-001",
    phone: "081234567890",
    email: "ahmad@klinik.id",
    clinicId: "c1",
    schedule: [
      { day: "Senin", startTime: "08:00", endTime: "12:00", maxPatients: 20 },
      { day: "Rabu", startTime: "08:00", endTime: "12:00", maxPatients: 20 },
      { day: "Jumat", startTime: "13:00", endTime: "17:00", maxPatients: 15 },
    ],
  },
  {
    id: "d2",
    name: "Dr. Lisa Permata",
    specialization: "Anak",
    licenseNumber: "SIP-2024-002",
    phone: "081234567896",
    email: "lisa@klinik.id",
    clinicId: "c1",
    schedule: [
      { day: "Selasa", startTime: "09:00", endTime: "13:00", maxPatients: 18 },
      { day: "Kamis", startTime: "09:00", endTime: "13:00", maxPatients: 18 },
      { day: "Sabtu", startTime: "08:00", endTime: "12:00", maxPatients: 15 },
    ],
  },
  {
    id: "d3",
    name: "Dr. Bambang Wahyu",
    specialization: "Umum",
    licenseNumber: "SIP-2024-003",
    phone: "081234567897",
    email: "bambang@klinik.id",
    clinicId: "c1",
    schedule: [
      { day: "Senin", startTime: "13:00", endTime: "17:00", maxPatients: 25 },
      { day: "Selasa", startTime: "13:00", endTime: "17:00", maxPatients: 25 },
      { day: "Rabu", startTime: "13:00", endTime: "17:00", maxPatients: 25 },
      { day: "Kamis", startTime: "13:00", endTime: "17:00", maxPatients: 25 },
    ],
  },
  {
    id: "d4",
    name: "Dr. Surya Prasetyo",
    specialization: "Jantung",
    licenseNumber: "SIP-2024-004",
    phone: "081234567898",
    email: "surya@medikaprima.id",
    clinicId: "c2",
    schedule: [
      { day: "Senin", startTime: "08:00", endTime: "13:00", maxPatients: 20 },
      { day: "Rabu", startTime: "08:00", endTime: "13:00", maxPatients: 20 },
      { day: "Jumat", startTime: "08:00", endTime: "13:00", maxPatients: 20 },
    ],
  },
  {
    id: "d5",
    name: "Dr. Nita Wijaya",
    specialization: "Ortopedi",
    licenseNumber: "SIP-2024-005",
    phone: "081234567899",
    email: "nita@medikaprima.id",
    clinicId: "c2",
    schedule: [
      { day: "Selasa", startTime: "09:00", endTime: "14:00", maxPatients: 18 },
      { day: "Kamis", startTime: "09:00", endTime: "14:00", maxPatients: 18 },
      { day: "Sabtu", startTime: "08:00", endTime: "12:00", maxPatients: 15 },
    ],
  },
  {
    id: "d6",
    name: "Dr. Yusuf Rahman",
    specialization: "Penyakit Dalam",
    licenseNumber: "SIP-2024-006",
    phone: "081234567900",
    email: "yusuf@medikaprima.id",
    clinicId: "c2",
    schedule: [
      { day: "Senin", startTime: "14:00", endTime: "18:00", maxPatients: 22 },
      { day: "Selasa", startTime: "14:00", endTime: "18:00", maxPatients: 22 },
      { day: "Rabu", startTime: "14:00", endTime: "18:00", maxPatients: 22 },
      { day: "Kamis", startTime: "14:00", endTime: "18:00", maxPatients: 22 },
    ],
  },
  {
    id: "d7",
    name: "drg. Kevin Santoso",
    specialization: "Gigi Umum",
    licenseNumber: "SIP-2024-007",
    phone: "081234567901",
    email: "kevin@senyumindah.id",
    clinicId: "c3",
    schedule: [
      { day: "Senin", startTime: "09:00", endTime: "13:00", maxPatients: 12 },
      { day: "Rabu", startTime: "09:00", endTime: "13:00", maxPatients: 12 },
      { day: "Jumat", startTime: "09:00", endTime: "13:00", maxPatients: 12 },
    ],
  },
  {
    id: "d8",
    name: "drg. Putri Amelia",
    specialization: "Ortodonti",
    licenseNumber: "SIP-2024-008",
    phone: "081234567902",
    email: "putri@senyumindah.id",
    clinicId: "c3",
    schedule: [
      { day: "Selasa", startTime: "10:00", endTime: "14:00", maxPatients: 10 },
      { day: "Kamis", startTime: "10:00", endTime: "14:00", maxPatients: 10 },
      { day: "Sabtu", startTime: "09:00", endTime: "13:00", maxPatients: 10 },
    ],
  },
]

export const APPOINTMENTS: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Budi Setiawan",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-28",
    time: "09:00",
    type: "konsultasi",
    status: "selesai",
    complaint: "Demam dan sakit kepala",
    clinicId: "c1",
    queueNumber: 1,
  },
  {
    id: "a2",
    patientId: "p2",
    patientName: "Siti Rahayu",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-28",
    time: "09:30",
    type: "kontrol",
    status: "berlangsung",
    complaint: "Kontrol tekanan darah",
    clinicId: "c1",
    queueNumber: 2,
  },
  {
    id: "a3",
    patientId: "p3",
    patientName: "Joko Susanto",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-28",
    time: "10:00",
    type: "konsultasi",
    status: "menunggu",
    complaint: "Nyeri dada",
    clinicId: "c1",
    queueNumber: 3,
  },
  {
    id: "a4",
    patientId: "p4",
    patientName: "Dewi Lestari",
    doctorId: "d2",
    doctorName: "Dr. Lisa Permata",
    date: "2026-05-28",
    time: "09:00",
    type: "konsultasi",
    status: "menunggu",
    complaint: "Batuk pilek",
    clinicId: "c1",
    queueNumber: 1,
  },
  {
    id: "a5",
    patientId: "p5",
    patientName: "Rizki Pratama",
    doctorId: "d3",
    doctorName: "Dr. Bambang Wahyu",
    date: "2026-05-28",
    time: "13:00",
    type: "tindakan",
    status: "menunggu",
    complaint: "Luka jahit",
    clinicId: "c1",
    queueNumber: 1,
  },
  {
    id: "a6",
    patientId: "p6",
    patientName: "Anita Kusuma",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-29",
    time: "08:00",
    type: "konsultasi",
    status: "menunggu",
    complaint: "Sesak nafas",
    clinicId: "c1",
    queueNumber: 1,
  },
  {
    id: "a7",
    patientId: "p7",
    patientName: "Hendra Gunawan",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-28",
    time: "10:30",
    type: "darurat",
    status: "menunggu",
    complaint: "Kecelakaan",
    clinicId: "c1",
    queueNumber: 4,
  },
  {
    id: "a8",
    patientId: "p8",
    patientName: "Fitri Handayani",
    doctorId: "d2",
    doctorName: "Dr. Lisa Permata",
    date: "2026-05-28",
    time: "09:30",
    type: "kontrol",
    status: "menunggu",
    complaint: "Kontrol kehamilan",
    clinicId: "c1",
    queueNumber: 2,
  },
  {
    id: "a9",
    patientId: "p9",
    patientName: "Tono Wibowo",
    doctorId: "d4",
    doctorName: "Dr. Surya Prasetyo",
    date: "2026-05-28",
    time: "08:00",
    type: "kontrol",
    status: "selesai",
    complaint: "Kontrol jantung rutin",
    clinicId: "c2",
    queueNumber: 1,
  },
  {
    id: "a10",
    patientId: "p10",
    patientName: "Lia Susanto",
    doctorId: "d4",
    doctorName: "Dr. Surya Prasetyo",
    date: "2026-05-28",
    time: "09:00",
    type: "konsultasi",
    status: "berlangsung",
    complaint: "Dada berdebar",
    clinicId: "c2",
    queueNumber: 2,
  },
  {
    id: "a11",
    patientId: "p11",
    patientName: "Bram Hadi",
    doctorId: "d4",
    doctorName: "Dr. Surya Prasetyo",
    date: "2026-05-28",
    time: "10:00",
    type: "tindakan",
    status: "menunggu",
    complaint: "EKG dan echo jantung",
    clinicId: "c2",
    queueNumber: 3,
  },
  {
    id: "a12",
    patientId: "p12",
    patientName: "Eka Putri",
    doctorId: "d5",
    doctorName: "Dr. Nita Wijaya",
    date: "2026-05-28",
    time: "09:00",
    type: "konsultasi",
    status: "menunggu",
    complaint: "Nyeri lutut kanan",
    clinicId: "c2",
    queueNumber: 1,
  },
  {
    id: "a13",
    patientId: "p13",
    patientName: "Dian Pratiwi",
    doctorId: "d7",
    doctorName: "drg. Kevin Santoso",
    date: "2026-05-28",
    time: "09:00",
    type: "tindakan",
    status: "selesai",
    complaint: "Cabut gigi geraham",
    clinicId: "c3",
    queueNumber: 1,
  },
  {
    id: "a14",
    patientId: "p14",
    patientName: "Rudi Hartono",
    doctorId: "d7",
    doctorName: "drg. Kevin Santoso",
    date: "2026-05-28",
    time: "10:00",
    type: "konsultasi",
    status: "berlangsung",
    complaint: "Sakit gigi berlubang",
    clinicId: "c3",
    queueNumber: 2,
  },
  {
    id: "a15",
    patientId: "p15",
    patientName: "Nana Sari",
    doctorId: "d8",
    doctorName: "drg. Putri Amelia",
    date: "2026-05-28",
    time: "10:00",
    type: "kontrol",
    status: "menunggu",
    complaint: "Kontrol behel",
    clinicId: "c3",
    queueNumber: 1,
  },
]

export const MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: "mr1",
    patientId: "p1",
    patientName: "Budi Setiawan",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-20",
    diagnosis: "Hipertensi Grade 1",
    symptoms: "Sakit kepala, pusing, tekanan darah 150/90",
    treatment: "Pemberian obat antihipertensi, diet rendah garam",
    prescriptions: [
      {
        id: "rx1",
        medicineName: "Amlodipine 5mg",
        dosage: "1 tablet",
        frequency: "1x sehari",
        duration: "30 hari",
        notes: "Diminum pagi hari",
      },
      {
        id: "rx2",
        medicineName: "Captopril 12.5mg",
        dosage: "1 tablet",
        frequency: "2x sehari",
        duration: "30 hari",
      },
    ],
    followUpDate: "2026-06-20",
    clinicId: "c1",
  },
  {
    id: "mr2",
    patientId: "p2",
    patientName: "Siti Rahayu",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-22",
    diagnosis: "Diabetes Mellitus Tipe 2",
    symptoms: "Sering haus, sering buang air kecil, gula darah 280 mg/dL",
    treatment: "Pemberian metformin, diet DM",
    prescriptions: [
      {
        id: "rx3",
        medicineName: "Metformin 500mg",
        dosage: "1 tablet",
        frequency: "3x sehari",
        duration: "30 hari",
        notes: "Diminum setelah makan",
      },
    ],
    followUpDate: "2026-06-22",
    clinicId: "c1",
  },
  {
    id: "mr3",
    patientId: "p3",
    patientName: "Joko Susanto",
    doctorId: "d1",
    doctorName: "Dr. Ahmad Santoso",
    date: "2026-05-25",
    diagnosis: "GERD (Gastroesophageal Reflux Disease)",
    symptoms: "Nyeri dada seperti terbakar, mual, sendawa",
    treatment: "Pemberian antasida, PPI, edukasi gaya hidup",
    prescriptions: [
      {
        id: "rx4",
        medicineName: "Omeprazole 20mg",
        dosage: "1 kapsul",
        frequency: "1x sehari",
        duration: "14 hari",
        notes: "Diminum 30 menit sebelum makan",
      },
      {
        id: "rx5",
        medicineName: "Antasida",
        dosage: "1 tablet",
        frequency: "3x sehari",
        duration: "7 hari",
        notes: "Kunyah sebelum ditelan",
      },
    ],
    clinicId: "c1",
  },
]

export const MEDICINES: Medicine[] = [
  {
    id: "m1",
    name: "Amoxicillin 500mg",
    category: "Antibiotik",
    unit: "Strip",
    stock: 150,
    minStock: 50,
    price: 15000,
    expiryDate: "2027-06-30",
    supplier: "Kimia Farma",
    clinicId: "c1",
  },
  {
    id: "m2",
    name: "Paracetamol 500mg",
    category: "Analgesik",
    unit: "Strip",
    stock: 300,
    minStock: 100,
    price: 5000,
    expiryDate: "2027-12-31",
    supplier: "Kalbe Farma",
    clinicId: "c1",
  },
  {
    id: "m3",
    name: "Amlodipine 5mg",
    category: "Antihipertensi",
    unit: "Strip",
    stock: 45,
    minStock: 50,
    price: 12000,
    expiryDate: "2027-03-31",
    supplier: "Dexa Medica",
    clinicId: "c1",
  },
  {
    id: "m4",
    name: "Metformin 500mg",
    category: "Antidiabetik",
    unit: "Strip",
    stock: 200,
    minStock: 80,
    price: 8000,
    expiryDate: "2027-09-30",
    supplier: "Kimia Farma",
    clinicId: "c1",
  },
  {
    id: "m5",
    name: "Omeprazole 20mg",
    category: "Antasida",
    unit: "Strip",
    stock: 120,
    minStock: 40,
    price: 18000,
    expiryDate: "2026-12-31",
    supplier: "Kalbe Farma",
    clinicId: "c1",
  },
  {
    id: "m6",
    name: "Cetirizine 10mg",
    category: "Antihistamin",
    unit: "Strip",
    stock: 180,
    minStock: 60,
    price: 10000,
    expiryDate: "2027-08-31",
    supplier: "Dexa Medica",
    clinicId: "c1",
  },
  {
    id: "m7",
    name: "Ibuprofen 400mg",
    category: "NSAID",
    unit: "Strip",
    stock: 25,
    minStock: 50,
    price: 7000,
    expiryDate: "2026-10-31",
    supplier: "Kimia Farma",
    clinicId: "c1",
  },
  {
    id: "m8",
    name: "Vitamin C 500mg",
    category: "Vitamin",
    unit: "Botol",
    stock: 90,
    minStock: 30,
    price: 25000,
    expiryDate: "2027-11-30",
    supplier: "Sido Muncul",
    clinicId: "c1",
  },
]

export const TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    patientId: "p1",
    patientName: "Budi Setiawan",
    appointmentId: "a1",
    date: "2026-05-28",
    items: [
      { description: "Biaya Konsultasi", quantity: 1, price: 150000, total: 150000 },
      { description: "Amlodipine 5mg", quantity: 30, price: 1500, total: 45000 },
      { description: "Captopril 12.5mg", quantity: 60, price: 800, total: 48000 },
    ],
    total: 243000,
    paid: 243000,
    paymentMethod: "bpjs",
    status: "lunas",
    clinicId: "c1",
  },
  {
    id: "t2",
    patientId: "p2",
    patientName: "Siti Rahayu",
    appointmentId: "a2",
    date: "2026-05-28",
    items: [
      { description: "Biaya Konsultasi", quantity: 1, price: 150000, total: 150000 },
      { description: "Metformin 500mg", quantity: 90, price: 800, total: 72000 },
    ],
    total: 222000,
    paid: 100000,
    paymentMethod: "tunai",
    status: "partial",
    clinicId: "c1",
  },
  {
    id: "t3",
    patientId: "p4",
    patientName: "Dewi Lestari",
    appointmentId: "a4",
    date: "2026-05-28",
    items: [
      { description: "Biaya Konsultasi", quantity: 1, price: 100000, total: 100000 },
      { description: "Paracetamol 500mg", quantity: 10, price: 500, total: 5000 },
      { description: "Amoxicillin 500mg", quantity: 15, price: 1500, total: 22500 },
    ],
    total: 127500,
    paid: 127500,
    paymentMethod: "transfer",
    status: "lunas",
    clinicId: "c1",
  },
  {
    id: "t4",
    patientId: "p5",
    patientName: "Rizki Pratama",
    appointmentId: "a5",
    date: "2026-05-27",
    items: [
      { description: "Biaya Tindakan Jahit", quantity: 1, price: 250000, total: 250000 },
      { description: "Biaya Konsultasi", quantity: 1, price: 100000, total: 100000 },
    ],
    total: 350000,
    paid: 0,
    paymentMethod: "tunai",
    status: "pending",
    clinicId: "c1",
  },
  {
    id: "t5",
    patientId: "p6",
    patientName: "Anita Kusuma",
    appointmentId: "a6",
    date: "2026-05-27",
    items: [
      { description: "Biaya Konsultasi", quantity: 1, price: 150000, total: 150000 },
      { description: "Salbutamol Inhaler", quantity: 1, price: 75000, total: 75000 },
    ],
    total: 225000,
    paid: 225000,
    paymentMethod: "asuransi",
    status: "lunas",
    clinicId: "c1",
  },
  {
    id: "t6",
    patientId: "p9",
    patientName: "Tono Wibowo",
    appointmentId: "a9",
    date: "2026-05-28",
    items: [
      { description: "Biaya Konsultasi Spesialis", quantity: 1, price: 350000, total: 350000 },
      { description: "EKG", quantity: 1, price: 150000, total: 150000 },
    ],
    total: 500000,
    paid: 500000,
    paymentMethod: "bpjs",
    status: "lunas",
    clinicId: "c2",
  },
  {
    id: "t7",
    patientId: "p10",
    patientName: "Lia Susanto",
    appointmentId: "a10",
    date: "2026-05-28",
    items: [
      { description: "Biaya Konsultasi Spesialis", quantity: 1, price: 350000, total: 350000 },
    ],
    total: 350000,
    paid: 0,
    paymentMethod: "asuransi",
    status: "pending",
    clinicId: "c2",
  },
  {
    id: "t8",
    patientId: "p12",
    patientName: "Eka Putri",
    appointmentId: "a12",
    date: "2026-05-27",
    items: [
      { description: "Biaya Konsultasi Ortopedi", quantity: 1, price: 400000, total: 400000 },
      { description: "Rontgen Lutut", quantity: 1, price: 250000, total: 250000 },
    ],
    total: 650000,
    paid: 650000,
    paymentMethod: "transfer",
    status: "lunas",
    clinicId: "c2",
  },
  {
    id: "t9",
    patientId: "p13",
    patientName: "Dian Pratiwi",
    appointmentId: "a13",
    date: "2026-05-28",
    items: [
      { description: "Cabut Gigi Geraham", quantity: 1, price: 250000, total: 250000 },
      { description: "Obat Anti Nyeri", quantity: 1, price: 50000, total: 50000 },
    ],
    total: 300000,
    paid: 300000,
    paymentMethod: "tunai",
    status: "lunas",
    clinicId: "c3",
  },
  {
    id: "t10",
    patientId: "p14",
    patientName: "Rudi Hartono",
    appointmentId: "a14",
    date: "2026-05-28",
    items: [
      { description: "Tambal Gigi Komposit", quantity: 1, price: 350000, total: 350000 },
    ],
    total: 350000,
    paid: 200000,
    paymentMethod: "tunai",
    status: "partial",
    clinicId: "c3",
  },
]

export const QUEUE_ITEMS: QueueItem[] = [
  {
    id: "q1",
    appointmentId: "a1",
    patientId: "p1",
    patientName: "Budi Setiawan",
    queueNumber: 1,
    type: "konsultasi",
    status: "selesai",
    registeredAt: "08:45",
    calledAt: "09:02",
    doctorName: "Dr. Ahmad Santoso",
    clinicId: "c1",
  },
  {
    id: "q2",
    appointmentId: "a2",
    patientId: "p2",
    patientName: "Siti Rahayu",
    queueNumber: 2,
    type: "kontrol",
    status: "berlangsung",
    registeredAt: "09:10",
    calledAt: "09:35",
    doctorName: "Dr. Ahmad Santoso",
    clinicId: "c1",
  },
  {
    id: "q3",
    appointmentId: "a3",
    patientId: "p3",
    patientName: "Joko Susanto",
    queueNumber: 3,
    type: "konsultasi",
    status: "menunggu",
    registeredAt: "09:30",
    doctorName: "Dr. Ahmad Santoso",
    clinicId: "c1",
  },
  {
    id: "q4",
    appointmentId: "a7",
    patientId: "p7",
    patientName: "Hendra Gunawan",
    queueNumber: 4,
    type: "darurat",
    status: "menunggu",
    registeredAt: "10:15",
    doctorName: "Dr. Ahmad Santoso",
    clinicId: "c1",
  },
  {
    id: "q5",
    appointmentId: "a4",
    patientId: "p4",
    patientName: "Dewi Lestari",
    queueNumber: 1,
    type: "konsultasi",
    status: "menunggu",
    registeredAt: "08:50",
    doctorName: "Dr. Lisa Permata",
    clinicId: "c1",
  },
  {
    id: "q6",
    appointmentId: "a8",
    patientId: "p8",
    patientName: "Fitri Handayani",
    queueNumber: 2,
    type: "kontrol",
    status: "menunggu",
    registeredAt: "09:20",
    doctorName: "Dr. Lisa Permata",
    clinicId: "c1",
  },
  {
    id: "q7",
    appointmentId: "a5",
    patientId: "p5",
    patientName: "Rizki Pratama",
    queueNumber: 1,
    type: "tindakan",
    status: "menunggu",
    registeredAt: "12:45",
    doctorName: "Dr. Bambang Wahyu",
    clinicId: "c1",
  },
  {
    id: "q8",
    appointmentId: "a9",
    patientId: "p9",
    patientName: "Tono Wibowo",
    queueNumber: 1,
    type: "kontrol",
    status: "selesai",
    registeredAt: "07:50",
    calledAt: "08:05",
    doctorName: "Dr. Surya Prasetyo",
    clinicId: "c2",
  },
  {
    id: "q9",
    appointmentId: "a10",
    patientId: "p10",
    patientName: "Lia Susanto",
    queueNumber: 2,
    type: "konsultasi",
    status: "berlangsung",
    registeredAt: "08:45",
    calledAt: "09:10",
    doctorName: "Dr. Surya Prasetyo",
    clinicId: "c2",
  },
  {
    id: "q10",
    appointmentId: "a11",
    patientId: "p11",
    patientName: "Bram Hadi",
    queueNumber: 3,
    type: "tindakan",
    status: "menunggu",
    registeredAt: "09:30",
    doctorName: "Dr. Surya Prasetyo",
    clinicId: "c2",
  },
  {
    id: "q11",
    appointmentId: "a12",
    patientId: "p12",
    patientName: "Eka Putri",
    queueNumber: 1,
    type: "konsultasi",
    status: "menunggu",
    registeredAt: "08:55",
    doctorName: "Dr. Nita Wijaya",
    clinicId: "c2",
  },
  {
    id: "q12",
    appointmentId: "a13",
    patientId: "p13",
    patientName: "Dian Pratiwi",
    queueNumber: 1,
    type: "tindakan",
    status: "selesai",
    registeredAt: "08:50",
    calledAt: "09:05",
    doctorName: "drg. Kevin Santoso",
    clinicId: "c3",
  },
  {
    id: "q13",
    appointmentId: "a14",
    patientId: "p14",
    patientName: "Rudi Hartono",
    queueNumber: 2,
    type: "konsultasi",
    status: "berlangsung",
    registeredAt: "09:40",
    calledAt: "10:05",
    doctorName: "drg. Kevin Santoso",
    clinicId: "c3",
  },
  {
    id: "q14",
    appointmentId: "a15",
    patientId: "p15",
    patientName: "Nana Sari",
    queueNumber: 1,
    type: "kontrol",
    status: "menunggu",
    registeredAt: "09:50",
    doctorName: "drg. Putri Amelia",
    clinicId: "c3",
  },
]
export const MONTHLY_STATS = [
  { month: "Jan", pendapatan: 45200000, pasien: 320 },
  { month: "Feb", pendapatan: 52100000, pasien: 380 },
  { month: "Mar", pendapatan: 48700000, pasien: 355 },
  { month: "Apr", pendapatan: 61500000, pasien: 420 },
  { month: "Mei", pendapatan: 58900000, pasien: 410 },
  { month: "Jun", pendapatan: 67200000, pasien: 480 },
  { month: "Jul", pendapatan: 72400000, pasien: 510 },
  { month: "Agu", pendapatan: 69800000, pasien: 495 },
  { month: "Sep", pendapatan: 75300000, pasien: 530 },
  { month: "Okt", pendapatan: 81200000, pasien: 570 },
  { month: "Nov", pendapatan: 78600000, pasien: 555 },
  { month: "Des", pendapatan: 89400000, pasien: 620 },
]

export const CLINIC_MONTHLY_STATS: Record<string, typeof MONTHLY_STATS> = {
  c1: MONTHLY_STATS,
  c2: [
    { month: "Jan", pendapatan: 98500000, pasien: 510 },
    { month: "Feb", pendapatan: 112300000, pasien: 590 },
    { month: "Mar", pendapatan: 105800000, pasien: 560 },
    { month: "Apr", pendapatan: 131200000, pasien: 640 },
    { month: "Mei", pendapatan: 127400000, pasien: 620 },
    { month: "Jun", pendapatan: 145600000, pasien: 700 },
    { month: "Jul", pendapatan: 158900000, pasien: 740 },
    { month: "Agu", pendapatan: 152300000, pasien: 720 },
    { month: "Sep", pendapatan: 163700000, pasien: 770 },
    { month: "Okt", pendapatan: 178500000, pasien: 830 },
    { month: "Nov", pendapatan: 171200000, pasien: 800 },
    { month: "Des", pendapatan: 195600000, pasien: 890 },
  ],
  c3: [
    { month: "Jan", pendapatan: 18400000, pasien: 98 },
    { month: "Feb", pendapatan: 21300000, pasien: 112 },
    { month: "Mar", pendapatan: 19800000, pasien: 105 },
    { month: "Apr", pendapatan: 24600000, pasien: 128 },
    { month: "Mei", pendapatan: 23100000, pasien: 120 },
    { month: "Jun", pendapatan: 26800000, pasien: 140 },
    { month: "Jul", pendapatan: 29400000, pasien: 152 },
    { month: "Agu", pendapatan: 27600000, pasien: 145 },
    { month: "Sep", pendapatan: 31200000, pasien: 162 },
    { month: "Okt", pendapatan: 33800000, pasien: 175 },
    { month: "Nov", pendapatan: 31500000, pasien: 168 },
    { month: "Des", pendapatan: 36900000, pasien: 192 },
  ],
}

export const DIAGNOSIS_STATS = [
  { name: "Hipertensi", value: 28 },
  { name: "Diabetes", value: 22 },
  { name: "ISPA", value: 18 },
  { name: "Gastritis", value: 15 },
  { name: "Lainnya", value: 17 },
]

export const CLINIC_DIAGNOSIS_STATS: Record<string, typeof DIAGNOSIS_STATS> = {
  c1: DIAGNOSIS_STATS,
  c2: [
    { name: "Penyakit Jantung", value: 32 },
    { name: "Gangguan Tulang", value: 25 },
    { name: "Diabetes", value: 18 },
    { name: "Stroke", value: 12 },
    { name: "Lainnya", value: 13 },
  ],
  c3: [
    { name: "Karies Gigi", value: 38 },
    { name: "Periodontitis", value: 25 },
    { name: "Maloklusi", value: 18 },
    { name: "Abses Gigi", value: 12 },
    { name: "Lainnya", value: 7 },
  ],
}

export const VISIT_TREND = [
  { day: "Sen", kunjungan: 45 },
  { day: "Sel", kunjungan: 52 },
  { day: "Rab", kunjungan: 38 },
  { day: "Kam", kunjungan: 61 },
  { day: "Jum", kunjungan: 55 },
  { day: "Sab", kunjungan: 42 },
]

export const CLINIC_VISIT_TREND: Record<string, typeof VISIT_TREND> = {
  c1: VISIT_TREND,
  c2: [
    { day: "Sen", kunjungan: 82 },
    { day: "Sel", kunjungan: 95 },
    { day: "Rab", kunjungan: 74 },
    { day: "Kam", kunjungan: 108 },
    { day: "Jum", kunjungan: 97 },
    { day: "Sab", kunjungan: 68 },
  ],
  c3: [
    { day: "Sen", kunjungan: 18 },
    { day: "Sel", kunjungan: 22 },
    { day: "Rab", kunjungan: 15 },
    { day: "Kam", kunjungan: 25 },
    { day: "Jum", kunjungan: 21 },
    { day: "Sab", kunjungan: 30 },
  ],
}
